version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say and print hello world"
          command: echo "text to output here" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print-output-file:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - attach_workspace:
            at: ~/
        - run:
            name: "view-output-file"
            command: cat ~/output.txt
workflows:
  default:
    jobs:
      - say-hello
      - print-output-file:
          requires:
            - say-hello